# Sample values file for using S3 storage with IAM role binding

## Global configuration
global:
  env: production

## Outline application configuration
outline:
  replicaCount: 1

  image:
    repository: outlinewiki/outline
    tag: latest
    pullPolicy: IfNotPresent

  service:
    type: ClusterIP
    port: 80

  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      cert-manager.io/cluster-issuer: letsencrypt-prod
    hosts:
      - host: wiki.example.com
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: outline-tls
        hosts:
          - wiki.example.com

  # Configure S3 storage with IAM role
  # Note: FILE_STORAGE will be automatically set to "s3" based on this setting
  storage:
    type: s3
    s3:
      useServiceAccount: true
      region: "us-east-1"
      bucket: "your-outline-bucket"
      bucketUrl: "https://your-outline-bucket.s3.amazonaws.com"
      forcePathStyle: false
      acl: "private"

  # Configure service account for IAM role binding
  serviceAccount:
    create: true
    annotations:
      # For AWS EKS with IAM Roles for Service Accounts (IRSA)
      eks.amazonaws.com/role-arn: "arn:aws:iam::123456789012:role/outline-s3-role"
      # For GCP with Workload Identity
      # iam.gke.io/gcp-service-account: "outline-sa@your-project.iam.gserviceaccount.com"
      # For Azure Kubernetes Service with AAD Pod Identity
      # aadpodidbinding: "outline-s3-identity"

  # Application configuration
  # Non-sensitive environment variables
  env:
    URL: "https://wiki.example.com"
    PORT: 3000
    DEFAULT_LANGUAGE: "en_US"

  # Secrets configuration
  # All sensitive information should be defined here
  secrets:
    # Core secrets - generate using: openssl rand -hex 32
    SECRET_KEY: "replace-with-a-random-key"
    UTILS_SECRET: "replace-with-a-random-key"

    # Alternatively, reference existing secrets:
    # SECRET_KEY:
    #   secretName: "existing-secret"
    #   secretKey: "secret-key-field"
    # UTILS_SECRET:
    #   secretName: "existing-secret"
    #   secretKey: "utils-secret-field"

    # Authentication configuration - choose only one type
    auth:
      type: "google"  # Options: google, slack, azure, oidc

      # Google OAuth
      google:
        CLIENT_ID: "your-google-client-id"
        CLIENT_SECRET: "your-google-client-secret"
        # Alternatively, reference existing secrets:
        # CLIENT_ID:
        #   secretName: "google-oauth"
        #   secretKey: "client-id"
        # CLIENT_SECRET:
        #   secretName: "google-oauth"
        #   secretKey: "client-secret"

      # Slack OAuth (uncomment to use)
      # slack:
      #   CLIENT_ID: "your-slack-client-id"
      #   CLIENT_SECRET: "your-slack-client-secret"
      #   # Alternatively, reference existing secrets:
      #   # CLIENT_ID:
      #   #   secretName: "slack-oauth"
      #   #   secretKey: "client-id"
      #   # CLIENT_SECRET:
      #   #   secretName: "slack-oauth"
      #   #   secretKey: "client-secret"

      # Azure OAuth (uncomment to use)
      # azure:
      #   CLIENT_ID: "your-azure-client-id"
      #   CLIENT_SECRET: "your-azure-client-secret"
      #   RESOURCE_APP_ID: "your-azure-resource-app-id"
      #   # Alternatively, reference existing secrets:
      #   # CLIENT_ID:
      #   #   secretName: "azure-oauth"
      #   #   secretKey: "client-id"
      #   # CLIENT_SECRET:
      #   #   secretName: "azure-oauth"
      #   #   secretKey: "client-secret"
      #   # RESOURCE_APP_ID:
      #   #   secretName: "azure-oauth"
      #   #   secretKey: "resource-app-id"

      # OIDC (uncomment to use)
      # oidc:
      #   CLIENT_ID: "your-oidc-client-id"
      #   CLIENT_SECRET: "your-oidc-client-secret"
      #   AUTH_URI: "https://your-oidc-provider/auth"
      #   TOKEN_URI: "https://your-oidc-provider/token"
      #   USERINFO_URI: "https://your-oidc-provider/userinfo"
      #   # Alternatively, reference existing secrets:
      #   # CLIENT_ID:
      #   #   secretName: "oidc-auth"
      #   #   secretKey: "client-id"
      #   # CLIENT_SECRET:
      #   #   secretName: "oidc-auth"
      #   #   secretKey: "client-secret"
      #   # AUTH_URI:
      #   #   secretName: "oidc-auth"
      #   #   secretKey: "auth-uri"
      #   # TOKEN_URI:
      #   #   secretName: "oidc-auth"
      #   #   secretKey: "token-uri"
      #   # USERINFO_URI:
      #   #   secretName: "oidc-auth"
      #   #   secretKey: "userinfo-uri"

  # Local persistence not needed when using S3
  persistence:
    enabled: false

## PostgreSQL configuration
## DATABASE_URL will be automatically generated and stored in a Secret
postgresql:
  enabled: true
  postgresqlUsername: outline
  postgresqlPassword: "replace-with-secure-password"
  postgresqlDatabase: outline
  persistence:
    enabled: true
    size: 8Gi

## Redis configuration
## REDIS_URL will be automatically generated and stored in a Secret
redis:
  enabled: true
  password: "replace-with-secure-password"
  persistence:
    enabled: true
    size: 1Gi
