apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "outline.fullname" . }}-config
  labels:
    {{- include "outline.labels" . | nindent 4 }}
data:
  NODE_ENV: {{ .Values.global.env | quote }}
  {{- range $key, $value := .Values.env }}
  {{- if and (ne $key "FILE_STORAGE") (not (contains "CLIENT_ID" $key)) (not (contains "CLIENT_SECRET" $key)) (not (contains "OAUTH" $key)) (not (contains "AUTH_URI" $key)) (not (contains "TOKEN_URI" $key)) (not (contains "USERINFO_URI" $key)) }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- end }}
